### ISSUE TITLE
Log::Log4perl::Catalyst has no version

### ISSUE THREAD

**Issue by eserte** [mschilli/log4perl#105]
At least CPAN.pm thinks that Log::Log4perl::Catalyst has no version:
```
cpan[1]> m Log::Log4perl::Catalyst
...
Module id = Log::Log4perl::Catalyst
    CPAN_USERID  MSCHILLI (Michael Schilli <m@perlmeister.com>)
    CPAN_VERSION undef
    CPAN_FILE    E/ET/ETJ/Log-Log4perl-1.53.tar.gz
    UPLOAD_DATE  2020-09-17
    MANPAGE      Log::Log4perl::Catalyst - Log::Log4perl Catalyst Module
    INST_FILE    /opt/perl-5.12.3/lib/site_perl/5.12.3/Log/Log4perl/Catalyst.pm
    INST_VERSION 1.49
```
Probably the reason is this line: https://metacpan.org/source/ETJ/Log-Log4perl-1.53/lib/Log/Log4perl/Catalyst.pm#L7
PAUSE looks only at the isolated `$VERSION` line when getting a module's version (for security reasons). It does not know anything about the `Log::Log4perl` module and the `$VERSION` value set there.

Possible fixes are:
* set a fixed version here
* create META.* files with a "provides" section

**Comment by mohawk2** [comment]
Set versions in that plus a couple of others, released as 1.54. Thanks!
