### ISSUE TITLE
Appender mail crashes at reading configuration

### ISSUE THREAD

**Issue by sblondeel** [mschilli/log4perl#106]
Hello,

Attached are two test cases:
- testing console only (works fine)
- testing console + mail (crashed when initializing Log4perl object)

I updated Log4perl and Specio (see $VERSION values) and still get the crash:

PERL5LIB=$HOME/lib/perl/share/perl perl console-and-mail-log4perl.pl 
$Log::Log4perl::VERSION=1.54
$Specio::VERSION=0.47
Validation failed for type named Bool declared in package Specio::Library::Builtins (/home/sblondeel/lib/perl/share/perl/5.28.1/Specio/Library/Builtins.pm) at line 69 in sub named (eval) with value 100

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Bool declared in package Specio::Library::Builtins (/home/sblondeel/lib/perl/share/perl/5.28.1/Specio/Library/Builtins.pm) at line 69 in sub named (eval) with value 100', 'type', 'Specio::Constraint::Simple=HASH(0x5654cdc94ab0)', 'value', 100) called at (eval 150) line 79
Eval::Closure::Sandbox_4::__ANON__('min_level', 'debug', 'name', 'mail', 'buffered', 100, 'subject', 'Log4perl speaking', 'to', 'sblondeel+log4perl@localhost', 'l4p_post_config_subs', 'ARRAY(0x5654cd5116a8)', 'l4p_depends_on', 'ARRAY(0x5654cd50cee8)', 'Threshold', 'WARN') called at /usr/share/perl5/Log/Dispatch/Email.pm line 39
Log::Dispatch::Email::new('Log::Dispatch::Email::MailSend', 'min_level', 'debug', 'name', 'mail', 'buffered', 100, 'subject', 'Log4perl speaking', 'to', 'sblondeel+log4perl@localhost', 'l4p_post_config_subs', 'ARRAY(0x5654cd5116a8)', 'l4p_depends_on', 'ARRAY(0x5654cd50cee8)', 'Threshold', 'WARN') called at /home/sblondeel/lib/perl/share/perl/5.28.1/Log/Log4perl/Appender.pm line 83
Log::Log4perl::Appender::new('Log::Log4perl::Appender', 'Log::Dispatch::Email::MailSend', 'name', 'mail', 'l4p_post_config_subs', 'ARRAY(0x5654cd5116a8)', 'l4p_depends_on', 'ARRAY(0x5654cd50cee8)', 'to', 'sblondeel+log4perl@localhost', 'subject', 'Log4perl speaking', 'Threshold', 'WARN', 'buffered', 100) called at /home/sblondeel/lib/perl/share/perl/5.28.1/Log/Log4perl/Config.pm line 413
Log::Log4perl::Config::create_appender_instance('HASH(0x5654cd404690)', 'mail', 'HASH(0x5654cd511678)', 'ARRAY(0x5654cd5116a8)', undef) called at /home/sblondeel/lib/perl/share/perl/5.28.1/Log/Log4perl/Config.pm line 305
Log::Log4perl::Config::_init('Log::Log4perl::Config', '/tmp/log4perl-console.conf') called at /home/sblondeel/lib/perl/share/perl/5.28.1/Log/Log4perl/Config.pm line 36
Log::Log4perl::Config::init('Log::Log4perl::Config', '/tmp/log4perl-console.conf') called at /home/sblondeel/lib/perl/share/perl/5.28.1/Log/Log4perl.pm line 253
Log::Log4perl::init('Log::Log4perl', '/tmp/log4perl-console.conf') called at console-and-mail-log4perl.pl line 36

[console-and-mail-log4perl.pl.txt](https://github.com/mschilli/log4perl/files/5945533/console-and-mail-log4perl.pl.txt)
[console-log4perl.pl.txt](https://github.com/mschilli/log4perl/files/5945534/console-log4perl.pl.txt)

**Comment by mohawk2** [comment]
Here is a cut-down repro case (please always report things with as minimal as possible a test-case :-):

```perl
use strict;
use warnings;
use File::Slurp qw( write_file );
use Log::Log4perl qw(get_logger :levels);
use Specio;
print STDERR "\$Log::Log4perl::VERSION=$Log::Log4perl::VERSION\n";
print STDERR "\$Specio::VERSION=$Specio::VERSION\n";

my $CONF_FILE = '/tmp/log4perl-console.conf';
write_file($CONF_FILE, << 'EOCONF');
log4perl.logger.mail=DEBUG, mail

log4perl.appender.mail=Log::Dispatch::Email::MailSend
log4perl.appender.mail.Threshold=WARN
log4perl.appender.mail.to=sblondeel+log4perl@localhost
log4perl.appender.mail.subject=Log4perl speaking
log4perl.appender.mail.layout=Log::Log4perl::Layout::PatternLayout
log4perl.appender.mail.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %H %P %-5p> %m%n
log4perl.appender.mail.buffered=100
EOCONF

Log::Log4perl->init($CONF_FILE);
get_logger('mail')->debug('Hello world!');
```

It does indeed throw an exception. This is because the `buffered` value needs to be a recognised `Bool` (0 or 1, see [the docs](https://metacpan.org/pod/Log::Dispatch::Email#CONSTRUCTOR)). If you change the value from 100 to 1, it then doesn't throw an exception.
