### ISSUE TITLE
worng package for get_logger

### ISSUE THREAD

**Issue by KES777** [mschilli/log4perl#64]
in your Log::Log4perl->get_logger you may initialize:

```
my $level =  $Log::Log4perl::caller_depth;
```

That will allow this to work:

```
$SIG{ __WARN__ } =  sub {
    local $Log::Log4perl::caller_depth =  $Log::Log4perl::caller_depth + 1;
    my $logger =  Log::Log4perl->get_logger;
    $logger->warn( '__WARN__ ', $Log::Log4perl::caller_depth, @_ );
};
```

With that init the get_logger will return logger with category where warn is called instead of package where $SIG{ __WARN__ } is defined;

Also you can think more deeply. It seems, to my mind, you can escape from $WRAPPERS_REGISTERED. Users just required to localize $Log::Log4perl::caller_depth as I did in my example

**Comment by mohawk2** [comment]
Can you spell out more clearly what problem you're trying to solve?

**Comment by KES777** [comment]
I do not remember already =(
