### ISSUE TITLE
Log::Log4perl::Filter::Boolean ignores order of filters in configuration

### ISSUE THREAD

**Issue by Sadrak** [mschilli/log4perl#70]
https://rt.cpan.org/Public/Bug/Display.html?id=110513

----

I use 2 boolean filters to combine simple regex-ignore filters (and chained them too):

log4perl.filter.AbortUserProtected     = sub { m!test a! }
log4perl.filter.AbortUserInactive      = sub { m!test b! }
log4perl.filter.AbortProjectInactive   = sub { m!test c! }
log4perl.filter.ProblemNewState        = sub { m!test d! }
log4perl.filter.ProblemPremiumProject  = sub { m!test e! }
log4perl.filter.ProblemInactiveProject = sub { m!test f! }
log4perl.filter.IgnoreTicket6851       = Log::Log4perl::Filter::Boolean
log4perl.filter.IgnoreTicket6851.logic = AbortUserProtected || AbortUserInactive || AbortProjectInactive || ProblemNewState || ProblemPremiumProject || ProblemInactiveProject

log4perl.filter.WrongContentLength   = sub { m!test 1! }
log4perl.filter.SessionMismatch      = sub { m!test 2! }
log4perl.filter.SessionTooLarge      = sub { m!test 3! }
log4perl.filter.InvalidBoundary      = sub { m!test 4! }
log4perl.filter.InvalidFieldName     = sub { m!test 5! }
log4perl.filter.InvalidUnicode       = sub { m!test 6! }
log4perl.filter.IgnoreUnwanted       = Log::Log4perl::Filter::Boolean
log4perl.filter.IgnoreUnwanted.logic = !WrongContentLength && !SessionMismatch && !SessionTooLarge && !InvalidBoundary && !InvalidFieldName && !InvalidUnicode && !IgnoreTicket6851

log4perl.appender.PanicApp.Filter = IgnoreUnwanted

----

in ~50% the loading of filters failed due to the following error:

Filter IgnoreTicket6851 required by Boolean filter, but not defined at /path/to/Log/Log4perl/Filter/Boolean.pm line 55.

After setting `_INTERNAL_DEBUG => 1` in Log::Log4perl::Filter::Boolean i see the problem:

Compiling '!WrongContentLength && !SessionMismatch && !SessionTooLarge && !InvalidBoundary && !InvalidFieldName && !InvalidUnicode && !IgnoreTicket6851'
Filter IgnoreTicket6851 required by Boolean filter, but not defined at /path/to/Log/Log4perl/Filter/Boolean.pm line 55.

VS

Compiling 'AbortUserProtected || AbortUserInactive || AbortProjectInactive || ProblemNewState || ProblemPremiumProject || ProblemInactiveProject'
func=        sub { 
            my($AbortProjectInactive, $AbortUserProtected, $AbortUserInactive, $ProblemNewState, $ProblemPremiumProject, $ProblemInactiveProject) = @_;
            &$AbortUserProtected || &$AbortUserInactive || &$AbortProjectInactive || &$ProblemNewState || &$ProblemPremiumProject || &$ProblemInactiveProject;
        }

Compiling '!WrongContentLength && !SessionMismatch && !SessionTooLarge && !InvalidBoundary && !InvalidFieldName && !InvalidUnicode && !IgnoreTicket6851'
func=        sub { 
            my($InvalidFieldName, $SessionTooLarge, $WrongContentLength, $IgnoreTicket6851, $SessionMismatch, $InvalidBoundary, $InvalidUnicode) = @_;
            !&$WrongContentLength && !&$SessionMismatch && !&$SessionTooLarge && !&$InvalidBoundary && !&$InvalidFieldName && !&$InvalidUnicode && !&$IgnoreTicket6851;
        }

----

The order of the boolean filters is not picked from the configuration. It is by random.

**Comment by Sadrak** [comment]
simple & easy "fix" would be to change the random behavior to predetermined behavior by adding a `sort` to the loading phase in Log::Log4perl::Config and make this well documented (in Log::Log4perl::Filter). This would allow to use number prefixed boolen filters to work as expected. And all other will fail (or success) not by random. My problem was that it worked 2 times in a row and than failed >1000 times in production in short times after i commited my changes ...
----
change `keys` to `sort keys`
here
https://github.com/mschilli/log4perl/blob/bc6284c2ec72a9bdfdac375129cdad445805968b/lib/Log/Log4perl/Config.pm#L232
and here
https://github.com/mschilli/log4perl/blob/bc6284c2ec72a9bdfdac375129cdad445805968b/lib/Log/Log4perl/Config.pm#L277
will be a simple fix.

**Comment by mschilli** [comment]
Yeah, the random order in which keys() returns the hash keys can have quite surprising results, when you least expect it, because especially with small sized hashes, it might take a while until the order actually flips. I've added "sort" to all "keys" calls in Config.pm. It's cheap because those hashes are small and the predictability and improved debugging is absolutely worth it. Thanks!

https://github.com/mschilli/log4perl/commit/ad3fb0783cb680c2adf1c85889d2a938217e761d
