### ISSUE TITLE
header_text option in Log::Log4perl::Appender::File incompatible with syswrite option

### ISSUE THREAD

**Issue by tmetro** [mschilli/log4perl#73]
If you set `syswrite=1` on the `Log::Log4perl::Appender::File` appender, the `header_text` option ceases to work. If you look at the code:

```perl
sub file_open {
    [...]
    if(defined $self->{header_text}) {
        [...]
        my $fh = $self->{fh};
        print $fh $self->{header_text};
    }
}
```
the cause is apparent. It is using `print` rather than `syswrite`, and you can't mix `syswrite` and STDIO on the same file descriptor.

Recommended fix would be to factor out the writter code from `log()` and call it from both `log()` and the above code.

**Comment by mschilli** [comment]
Thanks for reporting this issue, clearly a bug in file_open. The proper fix would be abstracting the print/syswrite wrapper as you've suggested but that would introduce another function call in the log() hotspot which would have a performance impact on heavy logging applications, so I went for a somewhat quick and dirty (but documented!) approach:
    https://github.com/mschilli/log4perl/commit/b2e9110a61dabd1d8e0c1073b21916eb64cf4d7d
