### ISSUE TITLE
Failed test 'header_text'

### ISSUE THREAD

**Issue by boxarocks** [mschilli/log4perl#77]
```
C:\>perl -v

This is perl 5, version 20, subversion 1 (v5.20.1) built for MSWin32-x64-multi-thread


t/026FileApp.t ............ 1/27
#   Failed test 'header_text'
#   at t/026FileApp.t line 459.
#          got: 'This is a nice header.
# This is a nice header.
# DEBUG - waah!
# '
#     expected: 'This is a nice header.
# DEBUG - waah!
# '
# Looks like you failed 1 test of 27.
t/026FileApp.t ............ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/27 subtests
        (less 8 skipped subtests: 18 okay)



Test Summary Report
-------------------
t/026FileApp.t          (Wstat: 256 Tests: 27 Failed: 1)
  Failed test:  23
  Non-zero exit status: 1
Files=73, Tests=740, 35 wallclock secs ( 0.44 usr +  0.05 sys =  0.48 CPU)
Result: FAIL
Failed 1/73 test programs. 1/740 subtests failed.
dmake.exe:  Error code 255, while making 'test_dynamic'
  MSCHILLI/Log-Log4perl-1.48.tar.gz
  C:\STRAWB~1\c\bin\dmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports MSCHILLI/Log-Log4perl-1.48.tar.gz
Stopping: 'install' failed for 'Log::Log4perl'.
```

**Comment by iafan** [comment]
Same here — doesn't install on Windows for the same reason. My Perl version:

```
perl -v

This is perl 5, version 16, subversion 1 (v5.16.1) built for MSWin32-x64-multi-thread
```

**Comment by prat0088** [comment]
Confirmed this is failing with Log::Log4perl 1.48.  It looks like #73 was intended to resolve the issue.

```
perl -v

This is perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x64-multi-thread
```
I'm looking at [log()](https://github.com/mschilli/log4perl/blob/b2e9110a61dabd1d8e0c1073b21916eb64cf4d7d/lib/Log/Log4perl/Appender/File.pm#L245), but I can't imagine why it would print two headers on Windows...

**Comment by mschilli** [comment]
#73 is fixed, please re-test and re-open if it's still an issue on Windows (which I unfortunately don't have easy access to).

**Comment by briandfoy** [comment]
I'm getting this issue with 1.49 on AppVeyor (a free CI system for Windows for those of us without our own Windows boxes):

https://ci.appveyor.com/project/briandfoy/ghojo/build/1.0.21

**Comment by zhiyuan-lin** [comment]
@mschilli The issue does not relate to the use of `syswrite`, it is just that the `unlink` on Windows works differently than Unix, it might be an issue with the Perl `CORE`.

If we use overwrite instead of append when opening the test file, the test will success.
This pull request fixed the issue:
https://github.com/mschilli/log4perl/pull/100
