### ISSUE TITLE
File appender: Perl 5.24 warns when syswrite is used with :utf8 handles

### ISSUE THREAD

**Issue by mballarin** [mschilli/log4perl#78]
Hi,

with Perl 5.24, any log write will cause a warning if the options "utf8" and "syswrite" are used together:

`syswrite() is deprecated on :utf8 handles at /usr/share/perl5/Log/Log4perl/Appender/File.pm line 272`

See https://rt.perl.org/Public/Bug/Display.html?id=125760 for the change in Perl.

Something like the following will silence the warning:
```
--- File.pm.orig        2017-01-17 16:35:18.869755923 +0000
+++ File.pm     2017-01-17 16:46:59.621725047 +0000
@@ -10,6 +10,7 @@
 use Fcntl;
 use File::Path;
 use File::Spec::Functions qw(splitpath);
+use Encode                qw(encode_utf8);
 use constant _INTERNAL_DEBUG => 0;
 
 ##################################################
@@ -163,10 +164,6 @@
         binmode $self->{fh}, $self->{binmode};
     }
 
-    if (defined $self->{utf8}) {
-        binmode $self->{fh}, ":utf8";
-    }
-
     if(defined $self->{header_text}) {
         if( $self->{header_text} !~ /\n\Z/ ) {
             $self->{header_text} .= "\n";
@@ -268,11 +265,13 @@
 
     my $fh = $self->{fh};
 
+    my $msg = $self->{utf8} ? encode_utf8($params{message}) : $params{message}; 
+
     if($self->{syswrite}) {
-       defined (syswrite $fh, $params{message}) or
+       defined (syswrite $fh, $msg) or
            die "Cannot syswrite to '$self->{filename}': $!";
     } else {
-        print $fh $params{message} or
+        print $fh $msg or
             die "Cannot write to '$self->{filename}': $!";
     }
 }
```

encode_utf8() is ancient, so it should not cause portability issues.

**Comment by mballarin** [comment]
Another thing I just noticed related to the "utf8" option: The existing code sets :utf8 binmode as soon as "utf8" is defined, i.e. even when set to zero. Is this intended?

I unintentionally changed this in the patch above.

**Comment by mschilli** [comment]
Thanks for bringing this up. I'm a little worried, though, that pulling in Encode.pm might add an unwanted dependency on older perls that don't have it in core and worked just fine without it. Guess we could check the perl version and figure out if it has Encode, and proceed as above, while leaving the old flow for older perls and make everyone happy? 

Also, your comment on utf8 being set even if it's set to 0 is well taken, I'll go ahead and fix that.

**Comment by mschilli** [comment]
Let me know if this works for you: https://github.com/mschilli/log4perl/commit/e8d8f6600312670a156399e220998dbd0832915f

**Comment by mschilli** [comment]
Released with Log::Log4perl 1.49. Thanks for bringing this up!

**Comment by mballarin** [comment]
Yes, works fine. Thanks for looking into this.
I'll open a Debian Bug report and see if this can still make it into Stretch.

**Comment by rufferson** [comment]
The same patch need to be applied to Socket appender otherwise it enters infinite retry loop:
```
Send to Log::Log4perl::Appender::Socket failed (Wide character in send at /usr/lib/perl5/5.30/core_perl/IO/Socket.pm line 285.
), retrying once... at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender/Socket.pm line 78.

```
Currently the only possibility to avoid that (apart of editing the file - which is not redistributable) is to monkey-patch the call with something like this
```
    my $log=\&Log::Log4perl::Appender::Socket::log;
    *Log::Log4perl::Appender::Socket::log = sub{
            my($s,%p)=@_;
            $p{message}=encode("utf8",$p{message});
            $log->($s,%p);
    };

```
