### ISSUE TITLE
`easy_init` with `autoflush`?

### ISSUE THREAD

**Issue by leegee** [mschilli/log4perl#85]
Would it be too much to add autoflush to `easy_init`? 

To get automatic flushing atm, I have to write a config, which I know isn't the end of the world, but it doesn't fit well with my lazy use of `:easy`.

**Comment by mohawk2** [comment]
I think it would be best if we stick with needing a config. However, would you like to PR a doc snippet that allows the lazy user to just copy-paste?

**Comment by mohawk2** [comment]
Thank you for engaging! I'm all in favour of laziness (being very lazy myself) :-)

**Comment by leegee** [comment]
Well, if 'easy' is supported it should be fully supported.
